# ---- temperature measurements ----
FROM arm32v7/python:3.7-slim

RUN apt-get update &&  apt install build-essential && apt-get install gcc

COPY requirements.txt /database/requirements.txt

RUN pip install -r /database/requirements.txt

COPY . /database

CMD ["python", "/database/temperature.py"]