# ---- clean database ----
FROM arm32v7/python:3.7-slim

RUN apt-get update &&  apt-get install build-essential -y && apt-get install gcc -y

COPY requirements.txt /database/requirements.txt

RUN pip install -r /database/requirements.txt

COPY . /database

CMD ["python", "/database/cleaner.py"]