# ---- temperature measurements ----
FROM arm32v7/python:3.7-slim

RUN apt-get update &&  apt-get install build-essential -y && apt-get autoremove -y && apt-get clean

COPY requirements.txt /database/requirements.txt

RUN pip install -r /database/requirements.txt

COPY . /database

CMD ["python", "/database/temperature.py"]